// Code generated by "stringer -trimprefix IMAGE_COMDAT_SELECT_ -type=ComdatSelection"; DO NOT EDIT.

package peflags

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IMAGE_COMDAT_SELECT_NODUPLICATES-1]
	_ = x[IMAGE_COMDAT_SELECT_ANY-2]
	_ = x[IMAGE_COMDAT_SELECT_SAME_SIZE-3]
	_ = x[IMAGE_COMDAT_SELECT_EXACT_MATCH-4]
	_ = x[IMAGE_COMDAT_SELECT_ASSOCIATIVE-5]
	_ = x[IMAGE_COMDAT_SELECT_LARGEST-6]
}

const _ComdatSelection_name = "NODUPLICATESANYSAME_SIZEEXACT_MATCHASSOCIATIVELARGEST"

var _ComdatSelection_index = [...]uint8{0, 12, 15, 24, 35, 46, 53}

func (i ComdatSelection) String() string {
	i -= 1
	if i >= ComdatSelection(len(_ComdatSelection_index)-1) {
		return "ComdatSelection(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ComdatSelection_name[_ComdatSelection_index[i]:_ComdatSelection_index[i+1]]
}
