// Code generated by "stringer -trimprefix IMAGE_SYM_CLASS_ -type=SymClass"; DO NOT EDIT.

package peflags

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IMAGE_SYM_CLASS_END_OF_FUNCTION-255]
	_ = x[IMAGE_SYM_CLASS_NULL-0]
	_ = x[IMAGE_SYM_CLASS_AUTOMATIC-1]
	_ = x[IMAGE_SYM_CLASS_EXTERNAL-2]
	_ = x[IMAGE_SYM_CLASS_STATIC-3]
	_ = x[IMAGE_SYM_CLASS_REGISTER-4]
	_ = x[IMAGE_SYM_CLASS_EXTERNAL_DEF-5]
	_ = x[IMAGE_SYM_CLASS_LABEL-6]
	_ = x[IMAGE_SYM_CLASS_UNDEFINED_LABEL-7]
	_ = x[IMAGE_SYM_CLASS_MEMBER_OF_STRUCT-8]
	_ = x[IMAGE_SYM_CLASS_ARGUMENT-9]
	_ = x[IMAGE_SYM_CLASS_STRUCT_TAG-10]
	_ = x[IMAGE_SYM_CLASS_MEMBER_OF_UNION-11]
	_ = x[IMAGE_SYM_CLASS_UNION_TAG-12]
	_ = x[IMAGE_SYM_CLASS_TYPE_DEFINITION-13]
	_ = x[IMAGE_SYM_CLASS_UNDEFINED_STATIC-14]
	_ = x[IMAGE_SYM_CLASS_ENUM_TAG-15]
	_ = x[IMAGE_SYM_CLASS_MEMBER_OF_ENUM-16]
	_ = x[IMAGE_SYM_CLASS_REGISTER_PARAM-17]
	_ = x[IMAGE_SYM_CLASS_BIT_FIELD-18]
	_ = x[IMAGE_SYM_CLASS_FAR_EXTERNAL-68]
	_ = x[IMAGE_SYM_CLASS_BLOCK-100]
	_ = x[IMAGE_SYM_CLASS_FUNCTION-101]
	_ = x[IMAGE_SYM_CLASS_END_OF_STRUCT-102]
	_ = x[IMAGE_SYM_CLASS_FILE-103]
	_ = x[IMAGE_SYM_CLASS_SECTION-104]
	_ = x[IMAGE_SYM_CLASS_WEAK_EXTERNAL-105]
	_ = x[IMAGE_SYM_CLASS_CLR_TOKEN-107]
}

const (
	_SymClass_name_0 = "NULLAUTOMATICEXTERNALSTATICREGISTEREXTERNAL_DEFLABELUNDEFINED_LABELMEMBER_OF_STRUCTARGUMENTSTRUCT_TAGMEMBER_OF_UNIONUNION_TAGTYPE_DEFINITIONUNDEFINED_STATICENUM_TAGMEMBER_OF_ENUMREGISTER_PARAMBIT_FIELD"
	_SymClass_name_1 = "FAR_EXTERNAL"
	_SymClass_name_2 = "BLOCKFUNCTIONEND_OF_STRUCTFILESECTIONWEAK_EXTERNAL"
	_SymClass_name_3 = "CLR_TOKEN"
	_SymClass_name_4 = "END_OF_FUNCTION"
)

var (
	_SymClass_index_0 = [...]uint8{0, 4, 13, 21, 27, 35, 47, 52, 67, 83, 91, 101, 116, 125, 140, 156, 164, 178, 192, 201}
	_SymClass_index_2 = [...]uint8{0, 5, 13, 26, 30, 37, 50}
)

func (i SymClass) String() string {
	switch {
	case i <= 18:
		return _SymClass_name_0[_SymClass_index_0[i]:_SymClass_index_0[i+1]]
	case i == 68:
		return _SymClass_name_1
	case 100 <= i && i <= 105:
		i -= 100
		return _SymClass_name_2[_SymClass_index_2[i]:_SymClass_index_2[i+1]]
	case i == 107:
		return _SymClass_name_3
	case i == 255:
		return _SymClass_name_4
	default:
		return "SymClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
